apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: reports.curator.operatefirst.io
spec:
  group: curator.operatefirst.io
  names:
    kind: Report
    listKind: ReportList
    plural: reports
    singular: report
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Report is the Schema for the reports API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ReportSpec defines the desired state of Report
            properties:
              namespace:
                type: string
              reportingEnd:
                format: date-time
                type: string
              reportingStart:
                format: date-time
                type: string
              schedule:
                properties:
                  cron:
                    properties:
                      expression:
                        type: string
                    type: object
                  daily:
                    properties:
                      hour:
                        format: int64
                        type: integer
                      minute:
                        format: int64
                        type: integer
                      second:
                        format: int64
                        type: integer
                    type: object
                  hourly:
                    properties:
                      minute:
                        format: int64
                        type: integer
                      second:
                        format: int64
                        type: integer
                    type: object
                  monthly:
                    properties:
                      dayOfMonth:
                        format: int64
                        type: integer
                      hour:
                        format: int64
                        type: integer
                      minute:
                        format: int64
                        type: integer
                      second:
                        format: int64
                        type: integer
                    type: object
                  period:
                    type: string
                  weekly:
                    properties:
                      dayOfWeek:
                        type: string
                      hour:
                        format: int64
                        type: integer
                      minute:
                        format: int64
                        type: integer
                      second:
                        format: int64
                        type: integer
                    type: object
                required:
                - period
                type: object
            required:
            - namespace
            - reportingEnd
            - reportingStart
            type: object
          status:
            description: ReportStatus defines the observed state of Report
            properties:
              conditions:
                type: string
              lastReportTime:
                format: date-time
                type: string
              nextReportTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
