# permissions for end users to edit reports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: report-editor-role
rules:
- apiGroups:
  - curator.operatorfirst.io
  resources:
  - reports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.operatorfirst.io
  resources:
  - reports/status
  verbs:
  - get
