apiVersion: curator.operatefirst.io/v1alpha1
kind: Report
metadata:
  name: day-report
spec:
  cronjobNamespace: koku-metrics-operator
  schedule: "0 */6 * * *"
  databaseName: curatordb
  databasePassword: M5rBgWkN8LfjeyI8
  databaseUser: curator
  databaseHostName: postgresql.koku-metrics-operator.svc
  databasePort: "5432"